from rest_framework.status import HTTP_400_BAD_REQUEST

ERROR_CB_URL_NOT_EXIST = (
    "ERROR_INVALID_CB_URL",
    HTTP_400_BAD_REQUEST,
    "INVALID CB_URL FIELD NAME OR FIELD VALUE",
)

ERROR_ORG_OF_INTEREST_CB_URL_NOT_EXIST = (
    "ERROR_INVALID_CB_URL",
    HTTP_400_BAD_REQUEST,
    "INVALID CB_URL FIELD NAME OR FIELD VALUE RELATED TO ORG OF INTEREST",
)
