# Generated by Django 3.2.13 on 2022-10-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0074_auto_20220530_0919'),
        ('t2', '0002_auto_20220919_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
